cluster: 
  hosts:
    proxy.domain.pl:
      ansible_host: "{{ terraform_outputs.zimbra_name_ip.value[-1][1]}}"
      zimbra_ldap: 'y'
      zimbra_logger: 'n'
      zimbra_mta: 'n'
      zimbra_dnscache: 'n'
      zimbra_snmp: 'y'
      zimbra_store: 'n'
      zimbra_apache: 'n'
      zimbra_spell: 'n'
      zimbra_convertd: 'n'
      zimbra_memcached: 'n'
      zimbra_proxy: 'n'
      zimbra_archiving: 'n'
      zimbra_chat: 'n'  
      zimbra_drive: 'n'

    mbx.domain.pl: 
      ansible_host: "{{ terraform_outputs.zimbra_name_ip.value[-1][2]}}"
      zimbra_ldap: 'n'
      zimbra_logger: 'y'
      zimbra_mta: 'n'
      zimbra_dnscache: 'n'
      zimbra_snmp: 'y'
      zimbra_store: 'y'
      zimbra_apache: 'y'
      zimbra_spell: 'y'
      zimbra_convertd: 'y'
      zimbra_memcached: 'n'
      zimbra_proxy: 'n'
      zimbra_archiving: 'n'
      zimbra_chat: 'n'  
      zimbra_drive: 'n'

    mta.domain.pl:
      ansible_host: "{{ terraform_outputs.zimbra_name_ip.value[-1][0]}}"
      zimbra_ldap: 'n'
      zimbra_logger: 'n'
      zimbra_mta: 'y'
      zimbra_dnscache: 'n'
      zimbra_snmp: 'y'
      zimbra_store: 'n'
      zimbra_spell: 'n'
      zimbra_memcached: 'y'
      zimbra_proxy: 'n'
      zimbra_drive: 'n'
      zimbra_convertd: 'n'
      zimbra_archiving: 'n'

  vars:
    terraform_outputs: "{{ lookup('file', 'terraform_outputs.json') | from_json }}"








    
